// Copyright (C) 2023-2026 Marek Zalewski aka Drwalin
//
// This file is part of bitscpp project under MIT License
// You should have received a copy of the MIT License along with this program.

#ifndef BITSCPP_V2_SPECIFICATION_HPP
#define BITSCPP_V2_SPECIFICATION_HPP

#include <cstdint>

namespace bitscpp
{
namespace v2
{
enum Type : uint8_t {
	V2_NULL = 0,
	V2_INT = 1,
	V2_FLOAT = 2,
	V2_BOOL = 3,
	V2_ARRAY = 4,
	V2_STRING = 5,
	V2_MAP = 6,
	V2_OBJECT_BEGIN = 7,
	V2_OBJECT_END = 8,

	V2_RESERVED = 9,
	
	V2_DETAIL_HALF = V2_FLOAT | 32,
	V2_DETAIL_BHALF = V2_FLOAT | 96,
	V2_DETAIL_DOUBLE = V2_FLOAT | 64,
	V2_DETAIL_CSTRING = V2_STRING | 32,
};

[[maybe_unused]] const uint8_t BEG_IMMEDIATE_INTEGER = 0x00;
[[maybe_unused]] const uint8_t END_IMMEDIATE_INTEGER = 0xA0; // exclusive

[[maybe_unused]] const uint8_t BEG_12B_INTEGER = 0xA0;
[[maybe_unused]] const uint8_t END_12B_INTEGER = 0xB0; // exclusive

[[maybe_unused]] const uint8_t BEG_SIZED_INTEGER = 0xB0;
[[maybe_unused]] const uint8_t END_SIZED_INTEGER = 0xB7; // exclusive

[[maybe_unused]] const uint8_t BEG_HALF = 0xB7;
[[maybe_unused]] const uint8_t BEG_FLOAT = 0xB8;
[[maybe_unused]] const uint8_t BEG_DOUBLE = 0xB9;
[[maybe_unused]] const uint8_t BEG_BFLOAT = 0xBA;


[[maybe_unused]] const Type headerTranslation[256] = {
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,

V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,
V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,

V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT, V2_INT,

V2_DETAIL_HALF, V2_FLOAT, V2_DETAIL_DOUBLE, V2_DETAIL_BHALF,

V2_BOOL,
V2_BOOL,
V2_OBJECT_BEGIN,
V2_OBJECT_END,

V2_MAP, V2_MAP,

V2_ARRAY, V2_ARRAY, V2_ARRAY, V2_ARRAY, V2_ARRAY, V2_ARRAY, V2_ARRAY, V2_ARRAY,
V2_ARRAY, V2_ARRAY, V2_ARRAY, V2_ARRAY, V2_ARRAY, V2_ARRAY, V2_ARRAY, V2_ARRAY,
V2_ARRAY,
V2_ARRAY,

V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING,
V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING,
V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING,
V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING,
V2_STRING, V2_STRING, V2_STRING, V2_STRING, V2_STRING,
V2_STRING,

V2_DETAIL_CSTRING,

V2_RESERVED, V2_RESERVED, V2_RESERVED, V2_RESERVED, V2_RESERVED, V2_RESERVED,





};
}
}

#endif
